POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "toid seether 9000",
  "author": "Chand Landster Evictius",
  "url": "http://www.dontforgetthetip.com",
  "likes": 6,
  "userId" : "64000a5bfbed2703837618dc"
}